export const teacher_homeworks = [
  {
    id: 1,
    name: 'Mathematics Homework Title 1',
    startDate: '2021-11-10T10:00:00.689Z',
    finishDate: '2021-11-14T00:00:00.689Z',
    isRequired: true,
    teacherName: 'Henry Evelyn',
    teacherId: 10,
    subject: 'Mathematics',
    numberOfSenders: 3,
    detail:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
  },
  {
    id: 2,
    name: 'Literature Homework Title 1',
    startDate: '2021-11-10T10:00:00.689Z',
    finishDate: '2021-11-14T00:00:00.689Z',
    isRequired: true,
    teacherName: 'Abello Charlotte',
    teacherId: 14,
    subject: 'Literature',
    numberOfSenders: 3,
    detail:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
  },
  {
    id: 3,
    name: 'History Homework Title 3',
    startDate: '2021-11-10T10:00:00.689Z',
    finishDate: '2021-11-14T00:00:00.689Z',
    isRequired: true,
    teacherId: 15,
    teacherName: 'Adina Isabella',
    subject: 'History',
    numberOfSenders: 3,
    detail:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
  },
  {
    id: 4,
    name: 'Mathematics Homework Title 2',
    startDate: '2021-11-10T10:00:00.689Z',
    finishDate: '2021-11-14T00:00:00.689Z',
    isRequired: true,
    teacherId: 10,
    teacherName: 'Henry Evelyn',
    subject: 'Mathematics',
    numberOfSenders: 3,
    detail:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
  },
  {
    id: 5,
    name: 'Literature Homework Title 2',
    startDate: '2021-11-10T10:00:00.689Z',
    finishDate: '2021-11-14T00:00:00.689Z',
    isRequired: true,
    teacherName: 'Abello Charlotte',
    teacherId: 14,
    subject: 'Literature',
    numberOfSenders: 3,
    detail:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
  },
  {
    id: 6,
    name: 'History Homework Title 2',
    startDate: '2021-11-10T10:00:00.689Z',
    finishDate: '2021-11-14T00:00:00.689Z',
    isRequired: true,
    teacherId: 15,
    teacherName: 'Adina Isabella',
    subject: 'History',
    numberOfSenders: 3,
    detail:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
  },
  {
    id: 7,
    name: 'History Homework Title 3',
    startDate: '2021-11-10T10:00:00.689Z',
    finishDate: '2021-11-14T00:00:00.689Z',
    isRequired: true,
    teacherId: 15,
    teacherName: 'Adina Isabella',
    subject: 'History',
    numberOfSenders: 3,
    detail:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
  },
  {
    id: 8,
    name: 'History Homework Title 1',
    startDate: '2021-11-10T10:00:00.689Z',
    finishDate: '2021-11-14T00:00:00.689Z',
    isRequired: true,
    teacherName: 'Joe New',
    teacherId: 16,
    subject: 'History',
    numberOfSenders: 3,
    detail:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
  },
  {
    id: 9,
    name: 'History Homework Title 2',
    startDate: '2021-11-10T10:00:00.689Z',
    finishDate: '2021-11-14T00:00:00.689Z',
    isRequired: true,
    teacherId: 16,
    teacherName: 'Joe New',
    subject: 'History',
    numberOfSenders: 3,
    detail:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
  },
  {
    id: 10,
    name: 'History Homework Title 3',
    startDate: '2021-11-10T10:00:00.689Z',
    finishDate: '2021-11-14T00:00:00.689Z',
    isRequired: true,
    teacherId: 16,
    teacherName: 'Joe New',
    subject: 'History',
    numberOfSenders: 3,
    detail:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
  },
];
