export const users = [
  {
    id: 1,
    namesurname: 'John Doe',
    username: 'johndoe',
    role: 'student',
    password: 'aaa',
  },
  {
    id: 2,
    namesurname: 'Liam Olivia',
    username: 'liamolivia',
    role: 'student',
    password: 'aaa',
  },
  {
    id: 3,
    namesurname: 'Oliver Ava',
    username: 'oliverava',
    role: 'student',
    password: 'aaa',
  },
  {
    id: 4,
    namesurname: 'Elijah Charlotte',
    username: 'elijahcharlotte',
    role: 'student',
    password: 'aaa',
  },
  {
    id: 5,
    namesurname: 'Lucas Amelia',
    username: 'lucasamelia',
    role: 'student',
    password: 'aaa',
  },
  {
    id: 6,
    namesurname: 'William Sophia',
    username: 'williamsophia',
    role: 'student',
    password: 'aaa',
  },
  {
    id: 7,
    namesurname: 'James Amelia',
    username: 'jamesamelia',
    role: 'student',
    password: 'aaa',
  },
  {
    id: 8,
    namesurname: 'Benjamin Isabella',
    username: 'benjaminisabella',
    role: 'student',
    password: 'aaa',
  },
  {
    id: 9,
    namesurname: 'Lucas Mia',
    username: 'lucasmia',
    role: 'student',
    password: 'aaa',
  },
  {
    id: 10,
    namesurname: 'Henry Evelyn',
    username: 'henryevelyn',
    role: 'teacher',
    password: 'aaa',
    subject: 'Mathematics',
  },
  {
    id: 11,
    namesurname: 'Alexander Aamina',
    username: 'alexanderaamina',
    role: 'teacher',
    password: 'aaa',
    subject: 'Mathematics',
  },
  {
    id: 12,
    namesurname: 'Abbie Harper',
    username: 'abbieharper',
    role: 'teacher',
    password: 'aaa',
    subject: 'Physical',
  },
  {
    id: 13,
    namesurname: 'Abdriel Amina',
    username: 'abdrielamina',
    role: 'teacher',
    password: 'aaa',
    subject: 'Chemical',
  },
  {
    id: 14,
    namesurname: 'Abello Charlotte',
    username: 'abellocharlotte',
    role: 'teacher',
    password: 'aaa',
    subject: 'Literature',
  },
  {
    id: 15,
    namesurname: 'Adina Isabella',
    username: 'adinaisabella',
    role: 'teacher',
    password: 'aaa',
    subject: 'History',
  },
  {
    id: 16,
    namesurname: 'Joe New',
    username: 'joenew',
    role: 'teacher',
    password: 'aaa',
    subject: 'History',
  },
];
